// Wires rust-core into the Android build. Hand-rolled instead of relying on
// org.mozilla.rust-android-gradle.rust-android: that plugin's jniLibs wiring has an
// unresolved "Duplicate resources" bug (3 fixes tried across a real debugging session,
// root cause not in the plugin's own single srcDir registration -- see git history and
// README.md for the full investigation). Removing it entirely sidesteps the bug instead
// of continuing to fight it: cross-compilation is a single direct `cargo ndk` invocation
// (no custom task-graph wiring needed), and the output lands straight in
// `src/main/jniLibs/<abi>/`, the same directory AGP's `com.android.library` plugin picks
// up automatically with zero extra plugins -- that's stock Android/Gradle behavior, not
// something needing rust-android-gradle at all.

plugins {
    id("com.android.library") version "8.5.0"
    id("org.jetbrains.kotlin.android") version "1.9.24"
}

android {
    // Matches uniffi's generated Kotlin package for this crate (see lib.rs's
    // `uniffi::setup_scaffolding!()` -- the generated package is `uniffi.<crate_name>`).
    namespace = "uniffi.ct_agent_android"
    compileSdk = 34

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        getByName("main") {
            // uniffi-bindgen's output directory, generated by generateUniffiBindings below
            // -- not checked into git (see .gitignore), regenerated on every build.
            kotlin.srcDir("${layout.buildDirectory.get()}/generated/uniffi/kotlin")
            // jniLibs.srcDirs left at its AGP default (src/main/jniLibs) deliberately --
            // cargoNdkBuild below writes straight there, so there is exactly ONE jniLibs
            // registration in this whole build, which is the actual fix: the plugin this
            // replaces had exactly one registration too (verified in its own source,
            // RustAndroidPlugin.kt), so the duplicate was never really about registration
            // count -- not fighting that mystery further, just removing every moving part
            // that isn't needed to produce a correct .aar.
        }
    }
}

dependencies {
    // Real build error, live-caught: without this, compileDebugKotlin failed with
    // "Unresolved reference: Pointer" and constructor-overload-ambiguity errors all through
    // the generated bindings -- UniFFI's Kotlin codegen emits JNA (`com.sun.jna.Pointer`
    // etc.) glue for the native FFI calls, and nothing declares that dependency by default.
    implementation("net.java.dev.jna:jna:5.14.0@aar")
}

// Cross-compiles all 4 ABIs and writes .so files directly into src/main/jniLibs/<abi>/ in
// one command -- cargo-ndk's own -o flag produces exactly that directory layout, no
// separate Copy task needed. Requires ANDROID_NDK_HOME (set in docker/Dockerfile) and the
// four `rustup target add`-ed triples (also set up there).
val jniLibsDir = "$projectDir/src/main/jniLibs"

tasks.register<Exec>("cargoNdkBuild") {
    workingDir = projectDir
    commandLine(
        "cargo", "ndk",
        "-t", "arm64-v8a",
        "-t", "armeabi-v7a",
        "-t", "x86",
        "-t", "x86_64",
        "-o", jniLibsDir,
        "build",
    )
    // .so files land under version control's reach (src/main/jniLibs) but are not meant
    // to be committed -- regenerated every build, real binaries, see .gitignore.
    outputs.dir(jniLibsDir)
}

tasks.register<Exec>("generateUniffiBindings") {
    dependsOn("cargoNdkBuild")
    val outDir = "${layout.buildDirectory.get()}/generated/uniffi/kotlin"
    doFirst { mkdir(outDir) }
    workingDir = projectDir
    commandLine(
        "cargo", "run", "--bin", "uniffi-bindgen", "--",
        "generate",
        "--library", "target/aarch64-linux-android/debug/libct_agent_android.so",
        "--language", "kotlin",
        "--out-dir", outDir,
    )
}

// Bindings and native libs must exist before Kotlin compilation/packaging touch them.
afterEvaluate {
    tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }
        .configureEach { dependsOn("generateUniffiBindings") }
    // preBuild is the earliest real task in every variant's graph (both app and library
    // modules) -- same principle a downstream rust-android-gradle consumer confirmed
    // working for the identical missing-native-lib symptom (real GitHub comment on
    // mozilla/rust-android-gradle#43), applied here to our own direct cargoNdkBuild task
    // instead of that plugin's.
    for (taskName in arrayOf("preDebugBuild", "preReleaseBuild")) {
        tasks.findByName(taskName)?.dependsOn("cargoNdkBuild")
    }
}
