// Wires rust-core into the Android build: cross-compile the cdylib for each ABI (via
// cargo-ndk, through the rust-android-gradle plugin), generate the UniFFI Kotlin bindings
// against the compiled library, then package both as a normal Android library module that
// app/build.gradle.kts's `implementation(project(":rust-core"))` can depend on.
//
// NOT VERIFIED: written without a local Gradle/Android/NDK toolchain (only `javac` was
// available in the environment this was authored in -- see README.md's "Not yet done").
// The plugin id/API shape below matches rust-android-gradle's documented usage as of when
// this was written; needs a real Gradle sync + `./gradlew :rust-core:assembleDebug` before
// this is trusted. If the plugin API has moved on, this is the first thing to fix.

plugins {
    id("com.android.library") version "8.5.0"
    id("org.jetbrains.kotlin.android") version "1.9.24"
    id("org.mozilla.rust-android-gradle.rust-android") version "0.9.6"
}

android {
    // Matches uniffi's generated Kotlin package for this crate (see lib.rs's
    // `uniffi::setup_scaffolding!()` -- the generated package is `uniffi.<crate_name>`).
    namespace = "uniffi.ct_agent_android"
    compileSdk = 34

    // Real build error, live-caught: without this, AGP's NDK auto-detection failed with
    // "NDK is not installed" even with the NDK physically present at
    // $ANDROID_SDK_ROOT/ndk/<version> and $ANDROID_NDK_HOME set -- AGP needs the version
    // pinned explicitly in the DSL, an env var alone isn't enough. Must match
    // docker/Dockerfile's `sdkmanager "ndk;<version>"` pin exactly.
    ndkVersion = "26.3.11579264"

    defaultConfig {
        minSdk = 26
    }

    // Real build error, live-caught: without this, compileDebugKotlin failed with
    // "Inconsistent JVM-target compatibility ... compileDebugJavaWithJavac (1.8) and
    // compileDebugKotlin (17)" -- AGP's Java compile defaults to 1.8, Kotlin here defaulted
    // to 17; app/build.gradle.kts already pins both, this module didn't.
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        getByName("main") {
            // uniffi-bindgen's output directory, generated by generateUniffiBindings below
            // -- not checked into git (see .gitignore), regenerated on every build.
            kotlin.srcDir("${layout.buildDirectory.get()}/generated/uniffi/kotlin")
            // Deliberately NOT also registering a jniLibs.srcDir here, real build error
            // live-caught: rust-android-gradle's own plugin already registers
            // build/rustJniLibs/android as a jniLibs source (that's its whole job) --
            // adding it a second time here made mergeDebugJniLibFolders see every .so
            // three times over and fail with "Duplicate resources".
        }
    }
}

dependencies {
    // Real build error, live-caught: without this, compileDebugKotlin failed with
    // "Unresolved reference: Pointer" and constructor-overload-ambiguity errors all through
    // the generated bindings -- UniFFI's Kotlin codegen emits JNA (`com.sun.jna.Pointer`
    // etc.) glue for the native FFI calls, and nothing declares that dependency by default.
    implementation("net.java.dev.jna:jna:5.14.0@aar")
}

cargo {
    module = "."
    libname = "ct_agent_android"
    targets = listOf("arm64", "arm", "x86", "x86_64")
    // Debug by default; release builds should override via -Pcargo.profile=release, kept
    // as a TODO rather than guessed at, since release-profile flags weren't part of the
    // scope this was written against.
}

tasks.register<Exec>("generateUniffiBindings") {
    dependsOn("cargoBuild")
    val outDir = "${layout.buildDirectory.get()}/generated/uniffi/kotlin"
    doFirst { mkdir(outDir) }
    workingDir = projectDir
    commandLine(
        "cargo", "run", "--bin", "uniffi-bindgen", "--",
        "generate",
        "--library", "target/aarch64-linux-android/debug/libct_agent_android.so",
        "--language", "kotlin",
        "--out-dir", outDir,
    )
}

// Bindings must exist before Kotlin compilation touches uniffi.ct_agent_android.*.
afterEvaluate {
    tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }
        .configureEach { dependsOn("generateUniffiBindings") }
}

// rust-core-debug.aar was missing the native .so libraries (classes.jar only, verified via
// unzip -l across multiple build attempts) -- matches mozilla/rust-android-gradle#43. First
// attempted fix, per that plugin's own issue #85, was making mergeDebugJniLibFolders depend
// on cargoBuild directly -- that corrected task *ordering* but a clean rebuild still hit a
// separate "Duplicate resources" error on every ABI. Replaced with the fix a maintainer of a
// DOWNSTREAM consumer actually confirmed working for the identical symptom (real GitHub
// comment on #43, not guessed): depend on preDebugBuild/preReleaseBuild instead -- these run
// early enough in the task graph that cargoBuild's output exists before the plugin's own
// (apparently duplicate-prone) jniLibs sourceSet registration is evaluated, sidestepping the
// duplicate-registration issue rather than fighting it head-on via the merge task itself.
afterEvaluate {
    for (taskName in arrayOf("preDebugBuild", "preReleaseBuild")) {
        tasks.findByName(taskName)?.dependsOn("cargoBuild")
    }
}
