// Wires rust-core into the Android build: cross-compile the cdylib for each ABI (via
// cargo-ndk, through the rust-android-gradle plugin), generate the UniFFI Kotlin bindings
// against the compiled library, then package both as a normal Android library module that
// app/build.gradle.kts's `implementation(project(":rust-core"))` can depend on.
//
// NOT VERIFIED: written without a local Gradle/Android/NDK toolchain (only `javac` was
// available in the environment this was authored in -- see README.md's "Not yet done").
// The plugin id/API shape below matches rust-android-gradle's documented usage as of when
// this was written; needs a real Gradle sync + `./gradlew :rust-core:assembleDebug` before
// this is trusted. If the plugin API has moved on, this is the first thing to fix.

plugins {
    id("com.android.library") version "8.5.0"
    id("org.jetbrains.kotlin.android") version "1.9.24"
    id("org.mozilla.rust-android-gradle.rust-android") version "0.9.6"
}

android {
    // Matches uniffi's generated Kotlin package for this crate (see lib.rs's
    // `uniffi::setup_scaffolding!()` -- the generated package is `uniffi.<crate_name>`).
    namespace = "uniffi.ct_agent_android"
    compileSdk = 34

    defaultConfig {
        minSdk = 26
    }

    sourceSets {
        getByName("main") {
            // uniffi-bindgen's output directory, generated by generateUniffiBindings below
            // -- not checked into git (see .gitignore), regenerated on every build.
            kotlin.srcDir("${layout.buildDirectory.get()}/generated/uniffi/kotlin")
            jniLibs.srcDir("${layout.buildDirectory.get()}/rustJniLibs/android")
        }
    }
}

cargo {
    module = "."
    libname = "ct_agent_android"
    targets = listOf("arm64", "arm", "x86", "x86_64")
    // Debug by default; release builds should override via -Pcargo.profile=release, kept
    // as a TODO rather than guessed at, since release-profile flags weren't part of the
    // scope this was written against.
}

tasks.register<Exec>("generateUniffiBindings") {
    dependsOn("cargoBuild")
    val outDir = "${layout.buildDirectory.get()}/generated/uniffi/kotlin"
    doFirst { mkdir(outDir) }
    workingDir = projectDir
    commandLine(
        "cargo", "run", "--bin", "uniffi-bindgen", "--",
        "generate",
        "--library", "target/aarch64-linux-android/debug/libct_agent_android.so",
        "--language", "kotlin",
        "--out-dir", outDir,
    )
}

// Bindings must exist before Kotlin compilation touches uniffi.ct_agent_android.*.
afterEvaluate {
    tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }
        .configureEach { dependsOn("generateUniffiBindings") }
}
